### ISSUE TITLE
Better Android support

### ISSUE THREAD

**Issue by mattbdean** [mattbdean/JRAW#188]
JRAW v1.0.0 will feature better Android support in an extension library similar to [JRAW-Android](https://github.com/thatJavaNerd/JRAW-Android) included as a subproject (`:android`) and available as its own project (jcenter: `net.dean.jraw:JRAW-Android:1.0.0`).

Here are some design changes for v1.0.0 (thanks to @Saketme):

- [x] Decouple Jackson from JsonModels
- [x] Allow passing a fullname directly instead of the full model to methods like `AccountManager#save(PublicContribution)`
- [x] Migrate from Jackson to Moshi
- [x] ~~Timber.Tree implementation~~ Don't log to stdout for Android
- [x] Android-specific documentation on [GitBook](https://mattbdean.gitbooks.io/jraw/content/)

@Saketme, @ccrama, or anyone else who has used JRAW on Android, is there anything that could be done from a design perspective to make JRAW more convenient for Android developers (authentication, storing/retrieving tokens, models, etc.)?

**Comment by Saketme** [comment]
Looks good! Nothing that I can think of right now.

**Comment by ccrama** [comment]
Have you considered making JRAW (or a version of JRAW) [Realm ](https://realm.io/)friendly? @fbis251  and I were planning on re-writing JRAW using Realm objects, but we didn't get very far with actually doing this as Realm doesn't support polymorphism, which makes a direct port pretty difficult (the 'Thing' class, for example, cannot have child classes that inherit it if it is a Realm object). The whole Paginator base of JRAW would have to be generalized to use Realm objects as well, but if v1 was not totally polymorphic, it would make a port much easier. 

IMO this would make Android integration and data persistence much easier to do! Just an idea, might be something to consider. If not, I am currently planning a rewrite of Slide's backend, and am going to make some sort of interface that bridges Realm with JRAW

**Comment by thatJavaNerd** [comment]
@ccrama I'm not sure how a non-inheritance-based model hierarchy would work with Jackson Databind. Realm sounds interesting, but I'm trying to keep v1 as small as possible. I've already replaced Guava's RateLimiter with another, smaller library and I'm writing a custom tree traverser for CommentNodes instead of using Guava's TreeTraverser.

How did you and @fbis251 imagine this Realm friendly port/bridge of JRAW?

**Comment by Saketme** [comment]
The problem with Realm is that it does not use plain Java objects, which makes it incompatible with a lot of things in Java. This is what you get when you fight the standard. For example, I'm a huge fan of AutoValue and last time I checked, it was impossible to use AutoValue with Realm.

**Comment by thatJavaNerd** [comment]
Gotcha. For now, I'd like for JRAW to be a plain Kotlin library. Maybe once we get v1 out we can look at extensions.

On a side note, how useful is CommentNode for Android, specifically `walkTree()`? How would it be easier for Android apps to utilize JRAW for creating comment section Views?

**Comment by fbis251** [comment]
I like your library, I have learned a lot while using it. My main gripe with JRAW is that it uses Jackson by default, and just including JRAW in your project increases the method count by 144%. As we all know Android has a [64k method limit](https://developer.android.com/studio/build/multidex.html) before we have to use multidex or proguard to bypass this limit.

As I mentioned over on #187 I would really like to see JRAW adopt Retrofit2 to perform API calls. This will allow each developer that uses JRAW to choose the [JSON library they prefer](https://github.com/square/retrofit/wiki/Converters).

As a demonstration and to back up my 144% figure above, I have taken some screenshots of some builds I performed including JRAW and Retrofit2 in a brand new Android project with some standard dependencies.

| Build | Method Count | Base Count Increase | Description | Screenshot |
| --    | --           | --                  | --          | --         |
| Standard APK                    | 17974  | 0 (+0%)       | Using support libraries provided by new project wizard: appcompat, constraint layout and design | [Base APK Size](https://user-images.githubusercontent.com/1300530/27065400-b417f766-4fb1-11e7-979e-38d714df876a.png) |
| Standard APK + JRAW             | 43878  | 25904 (+144%) | The bulk of the methods are from Jackson (9353), JRAW-specific methods are (1442) | [JRAW v0.9.0](https://user-images.githubusercontent.com/1300530/27065404-b41ea1b0-4fb1-11e7-93a9-c315289f33b9.png), [Jackson](https://user-images.githubusercontent.com/1300530/27065401-b418e63a-4fb1-11e7-8788-6a53ac7d48de.png), [JRAW-specific Count](https://user-images.githubusercontent.com/1300530/27065402-b41ab618-4fb1-11e7-94e2-b4e4f62fdb75.png) |
| Standard APK + Retrofit2        | 21454  | 3480 (+19%)   | Much smaller method count compared to Jackson | [Retrofit2 + GSON + Adapter](https://user-images.githubusercontent.com/1300530/27065403-b41becb8-4fb1-11e7-80bd-bc44db66d10f.png) | 
| Standard APK + Retrofit2 + JRAW | 22896  | 4922 (+27%)   | Predicted value summing the above count (21454), with JRAW-specific methods (1442) | |

You mention moving JRAW over to Kotlin, as of March 2016, the [kotlin stdlib defined 7191 methods](https://blog.jetbrains.com/kotlin/2016/03/kotlins-android-roadmap/). If the method counts stay the same, forcing JRAW users to include Jackson will leave fewer than 15k methods for their apps and other libraries.

Although at first I wasn't opposed to making JRAW easier to use with Realm as @ccrama mentioned above, I don't believe it will be possible since keeping the reddit API POJOs simple requires polymorphism. I think it's best to leave developers to implement their local storage using their database engine of choice since realm requires JNI which further increases the result APK size.

**Comment by thatJavaNerd** [comment]
I love the simplicity that Retrofit brings, but I don't think it's right for this library. Retrofit provides another level of abstraction that we already do ourselves. Correct me if I'm wrong, but wouldn't including Retrofit just increase the net method count of our applications? What is more advantageous about using OkHttp and migrating from Jackson to Gson instead of Retrofit + Gson + adapters?

Unless I'm missing something, here's how this would go:

If we replaced Jackson with Gson (assuming this is the smallest JSON library that meets our needs), our net dependencies would include Gson ([1342 methods](http://www.methodscount.com/?lib=com.google.code.gson%3Agson%3A2.7)), OkHttp ([2853](http://www.methodscount.com/?lib=com.squareup.okhttp3%3Aokhttp%3A3.8.0)), Kotlin stdlib ([6306](http://www.methodscount.com/?lib=org.jetbrains.kotlin%3Akotlin-stdlib%3A1.1.2-4)) (and maybe kotlin-reflect) for a total of 10,501 methods.

If we added Retrofit ([508](http://www.methodscount.com/?lib=com.squareup.retrofit2%3Aretrofit%3A2.1.0)), would it not require Gson and its Retrofit converter as well? It seems much simpler to simply ditch Jackson (which pulls in [30k+ methods](http://www.methodscount.com/?lib=com.fasterxml.jackson.module%3Ajackson-module-kotlin%3A2.8.7) when using the Kotlin module) and replace it with Gson.

Yes, we would be tightly coupling the library to Gson, but for the average use case, interacting with the JSON data directly should not be necessary and internalized as much as possible.

**Comment by Saketme** [comment]
You can technically use Retrofit without any JSON adapter and do the deserialization yourself, but yeah there's not a lot of benefits of using Retrofit over plain OkHttp. But I will let @fbis251 argue over this.

Putting that aside, can I recommend using Moshi instead of Gson? It's even more lightweight than GSON and is slightly faster because it does not use any runtime reflection like Gson.

**Comment by fbis251** [comment]
I'm okay with just switching Jackson out for a smaller JSON library, you make a good argument.

I would also prefer Moshi over GSON because under the hood it uses Okio's sources and sinks which play well with OkHttp which helps with the JSON deserialization speed. 

Moshi will only require [759 additional methods](http://www.methodscount.com/?lib=com.squareup.moshi%3Amoshi%3A1.5.0) since Okio is already part of JRAW via OkHttp

**Comment by thatJavaNerd** [comment]
That sounds like a plan to me, Moshi should be able to do everything that we use Jackson for. I'm gonna add it to the list.

**Comment by thatJavaNerd** [comment]
I've started the transition to Moshi on a separate branch (see [this commit](https://github.com/thatJavaNerd/JRAW/commit/41fd78f53473c7d61195f19157f6d61704a0d9de)).

**Comment by Saketme** [comment]
Sweet. Please me know if we can help. I've been using moshi for quite a while now :)

**Comment by thatJavaNerd** [comment]
I could use your advice. I'm having trouble trying to get Listings with generic children to deserialize. Could you take a look at [this test](https://github.com/thatJavaNerd/JRAW/blob/3935ae0ab8b5679b9d7fa5fe0cadaa229165c090/lib/src/test/kotlin/net/dean/jraw/test/MoshiTest.kt#L97)?

The only way I can get this to work currently is if I make a concrete Listing class for every RedditObject model, so instead of having this one class

```kotlin
data class Listing<T>(val before: String?, val after: String?, @Enveloped val children: List<T>)
```

we would have to have classes like these:

```kotlin
data class SubmissionListing(..., @Enveloped val children: List<Submission>)
data class SubredditListing(..., @Enveloped val children: List<Subreddit>)
// and so on
```

**Comment by Saketme** [comment]
Hey @thatJavaNerd, sorry for the late response. I'm going through the code, but as a person who hasn't started with Kotlin yet, I'm also having difficulties understanding the new syntax in that test. I will try pulling in your changes when I'm back home from office. 

In the meanwhile, I think the test is failing because Moshi supports custom type adapters per annotation: https://github.com/square/moshi#custom-field-names-with-json.

**Comment by thatJavaNerd** [comment]
It seems Moshi might not be an option until [square/moshi#309](https://github.com/square/moshi/issues/309) gets fixed, hopefully in 1.6.0

**Comment by Saketme** [comment]
Do you want to revert to 1.4 till that happens?

**Comment by thatJavaNerd** [comment]
The real problem here is Moshi's KotlinJsonAdapter does not support generics very well. The main benefits to using that specific adapter is that

 1. It refuses to assign null values to properties declared non-null in Kotlin (ClassJsonAdapter is not aware of Kotlin nullability)
 2. We get to keep on using [Kotlin data classes](https://kotlinlang.org/docs/reference/data-classes.html)

It turns out we can use AutoValue and the [Moshi extension](https://github.com/rharter/auto-value-moshi) to provide the same functionality. The only problem is we can't use JsonQualifiers on generic properties (see [rharter/auto-value-moshi#92](https://github.com/rharter/auto-value-moshi/issues/92)). I've submitted a [PR](https://github.com/rharter/auto-value-moshi/pull/93), so when that gets resolved we can take a serious look at migrating to Moshi.

**Comment by hzsweers** [comment]
Kotlin's reflection library also brings in like 18k methods

**Comment by ccrama** [comment]
Something I would also recommend is using a different logging library (or possibly slf4j-android), as SLF4J respects Android's wishes that it does not print debug messages to logcat, and therefore Android developers cannot see debug messages, even when set to logging mode always

**Comment by mattbdean** [comment]
JRAW only includes SLF4J's API as a compile time dependency. It's up to the user to specify an implementation for that API. Unless I'm missing something, it's the job of the implementation to do the actual logging.

From what I can tell, slf4j-android depends on the Android platform, so switching to it is an impossibility.

**Comment by hzsweers** [comment]
You could always just make your own thin interface and provide some batteries included stuff? A common pattern I see is a library having its own logger interface but then providing a `-timber` artifact with a `Timber.Tree` implementation that consumers can drop in easily

**Comment by mattbdean** [comment]
That's not a bad idea. We could definitely include an implementation in the future `:android` subproject.

**Comment by mattbdean** [comment]
Quick update: AutoValue + Moshi has completely replaced Jackson + Kotlin Reflect for all `:lib` code ([`0a4064b`](https://github.com/mattbdean/JRAW/commit/0a4064b8551d5bd96143cdfa84657fe3d568433a))

**Comment by Saketme** [comment]
So happy to hear this. I spend a lot of time working around the current json models for serializing/deserializing them. AutoValue is going to be awesome.

**Comment by mattbdean** [comment]
Another quick update: a barebones app with JRAW (master branch) and [JRAW-Android](https://github.com/mattbdean/JRAW-Android) (1.0.0 branch) takes up 33,638 total compared to 43,878 methods at v0.9.0 ([source](https://github.com/mattbdean/JRAW/issues/188#issuecomment-308002978)), a reduction of ~10,000 methods, or ~23%.

```
$ ./gradlew countDebugDexMethods

> Task :example-app:countDebugDexMethods
Total methods in example-app-debug.apk: 33638 (51.33% used)
Total fields in example-app-debug.apk:  18351 (28.00% used)
Total classes in example-app-debug.apk:  3855 (5.88% used)
Methods remaining in example-app-debug.apk: 31897
Fields remaining in example-app-debug.apk:  47184
Classes remaining in example-app-debug.apk:  61680
```

**Comment by Saketme** [comment]
Oh nice. Is that because you switched to Kotlin?

**Comment by mattbdean** [comment]
If anything the Kotlin stdlib adds more methods. The real savings was from no longer using Guava (in-house rate limiting and tree traversal) and switching from Jackson to Moshi.

**Comment by Saketme** [comment]
Wow, that is quite a huge change by simply removing Guava

**Comment by mattbdean** [comment]
I've rewritten [JRAW-Android](https://github.com/mattbdean/JRAW-Android/tree/1.0.0) for v1.0.0. Instead of using JakeWharton's Timber, I've gone for a simpler approach. [SimpleHttpLogger](https://github.com/mattbdean/JRAW/blob/832adfde19493e4937ee6db3e075fa4c78597eef/lib/src/main/kotlin/net/dean/jraw/http/SimpleHttpLogger.kt#L33) now takes a [LogAdapter](https://github.com/mattbdean/JRAW/blob/832adfde19493e4937ee6db3e075fa4c78597eef/lib/src/main/kotlin/net/dean/jraw/http/LogAdapter.kt) instead of a PrintStream. JRAW-Android provides a [LogAdapter that uses `android.util.Log`](https://github.com/mattbdean/JRAW-Android/blob/026d12080bba63a0f33f9965b6ef9c12d4d289b4/lib/src/main/kotlin/net/dean/jraw/android/SimpleAndroidLogAdapter.kt)
