### ISSUE TITLE
Get a submission from URL

### ISSUE THREAD

**Issue by mpivchev** [mattbdean/JRAW#202]
I want to save certain submission URLs to disk, and then display them again when it's required. How can I get a specific submission using its URL?

**Comment by mattbdean** [comment]
To look up a submission you'd have to know its ID, which you can get from parsing the submission's permalink URL:

`https://www.reddit.com/r/${subreddit}/comments/${id}/${title}`.

Once you find the ID, you can use [`redditClient.getSubmission(id)`](https://github.com/mattbdean/JRAW/blob/v0.9.0/src/main/java/net/dean/jraw/RedditClient.java#L264) to fetch the Submission.

I would recommend saving the submission ID instead of its URL.

**Comment by mpivchev** [comment]
Yup, saving the ID would be the better choice. Thanks for the help!
