### ISSUE TITLE
Implement Parcelable?

### ISSUE THREAD

**Issue by KirkBushman** [mattbdean/JRAW#204]
Hi, 
what is the intended method of passing objects like Submission or Subreddit between activities?

I see that you can serialize the object to a string using moshi, but serializing has a higher cost in terms of performance / GC, than Parcelable, if I remember correctly.
Would it not be better to have a Parcelable implementation?

I might be wrong,
thanks in advance.

**Comment by mattbdean** [comment]
As of right now JRAW is a plain Java library, so Parcelable isn't an option. Maybe @Saketme or @ccrama can weigh on this?

**Comment by Saketme** [comment]
Interesting question. I can think of two things right now. 

A) I've started using a pattern called "persistence as the single source of truth" in my app, where instead of passing objects across activities, you pass their IDs instead. This has greatly simplified the way I maintain state in my app because I can listen to changes in the DB and auto-update my UI. While this is not the solution you're looking for, is this something you can do, @KirkBushman?

B) Is serializing with Moshi really more expensive than Parcelable? Both follow a similar strategy of mapping fields to values at compile time by generating an "adapter".

**Comment by KirkBushman** [comment]
A) Seems a nice way to handle persistence, although it only works if the data is in your database (tell me if I'm wrong), which is not in this case. 

B) I don't know enough Moshi to enter the debate, the critic in the past with java Serializable was that it was creating temp objects that were triggering GC.
This is an article with perf comparison: http://www.developerphil.com/parcelable-vs-serializable/,
even thought nowadays, with more powerful SoC, it matters really nothing.
It would be nice to use with kotlin Parcelize annotation, which makes the process seamless.

**Comment by Saketme** [comment]
From what I understand from the article and its comments, serializable uses reflection and ends up allocating a lot more memory than parcelable. Since moshi's way of serializing objects similar to Parcelable -- that is, it also uses an adapter for skipping reflection, I think it should be fine.

More importantly, I don't think that you should be concerned about performance at all here when you only have one object. It's not like you need to serialize a list of million objects where performance will become a bottleneck. YAGNI.

**Comment by KirkBushman** [comment]
ok, alright.
I'll just use moshi.

Thanks for the clarification.
