### ISSUE TITLE
Exception in parsing JSON in comments()

### ISSUE THREAD

**Issue by tocttou** [mattbdean/JRAW#216]
Error: `Exception in thread "main" com.squareup.moshi.JsonDataException: Expected one of [public, private, restricted, gold_restricted, archived] but was user at path $.data.children[7].data.subreddit_type`

Happens "most of the times" in the following code:

```kotlin
        val comments = reddit.subreddit("all").comments().limit(50).build().iterator()
        for (i in 0..9) {
            TimeUnit.SECONDS.sleep(1)
            println(comments.next()[1].author)
        }
```

**Comment by mattbdean** [comment]
This only happens when comenting on a user subreddit (see [here](https://www.reddit.com/user/Shitty_Watercolour/) for an example). Should be an easy fix. All we'd have to do is add an enum value for the `user` type and handle future unknown values.

I'll fix this when I get home.

Also you don't have to manually sleep your thread, the library handles rate limiting for you.

**Comment by mattbdean** [comment]
Fixed! To use this patch you can either wait until v1.1.0 or use JitPack:

```groovy
repositories {
    maven { url 'https://jitpack.io' }
}
dependencies {
    compile 'com.github.mattbdean:JRAW:517837c'
}
```

**Comment by tocttou** [comment]
Thank you!
