### ISSUE TITLE
How to serialize Listing<NestedIdentifiable>

### ISSUE THREAD

**Issue by saket** [mattbdean/JRAW#259]
Hey matt. I'm trying to persist comments to my database, but I'm unable to understand how to find a json adapter. I have this simple data model:

```kotlin
@Entity
data class CachedSubmissionComments(
    val submissionId: String,

    val replies: Listing<NestedIdentifiable>,

    @PrimaryKey
    val request: ...
)
```

I'm using Room in my app and I've registered a type converter to let Room know how to serialize `replies: Listing<NestedIdentifiable>` using `JrawUtils.adapter<Listing<NestedIdentifiable>>(Enveloped::class.java)`, but I end up receiving a `DynamicAdapter` which fails with an `UnsupportedOperationException`.

I am trying to go through `RedditModelAdapterFactory`'s source, and it seems that I'll get a `StaticAdapter` only if the raw type (`Listing` in this case) is annotated with `RedditModel`. How do I solve this problem?

**Comment by mattbdean** [comment]
Related: #234, #237.

**Comment by saket** [comment]
Huh. I thought `ListingAdapter` was capable of handling this. Is that not the case?

**Comment by saket** [comment]
Hey @mattbdean, what do you think about this: https://github.com/saket/JRAW/commit/c4169035d1d886c75c894b7c3aa2ac631f4791b6

**Comment by mattbdean** [comment]
ListingAdapter knows about the direct properties of a Listing ("after" and "data"), but only knows how to deserialize "after" for sure. Since `data` can be a list of any type, it has to use a delegate JsonAdapter. ListingAdapter uses the Moshi instance it's given to find a JsonAdapter capable of handling `T` objects (given the type `Listing<T>`).

When `T` is `NestedIdentifiable`, the only adapter that can handle that is `DynamicAdapter`, and since `DynamicAdapter` is incapable of serialization, ListingAdapter is also incapable of serialization. When `T` is something like `Account`, the delegate is `StaticAdapter`, which handles serialization just fine, and so by extension, ListingAdapter handles it just fine as well.

**Comment by saket** [comment]
I see.

**Comment by saket** [comment]
Closing in favor of #237
